function out = apply_fd_pixel_codebook(codebook,newEnvironmentS21)
%APPLY_FD_PIXEL_CODEBOOK Pick the best stored state at each complex S21 point.
% Input is the model returned by training or the saved codebook.mat path.
if ischar(codebook) || isstring(codebook)
    loaded = load(codebook,'model');
    assert(isfield(loaded,'model'), 'The MAT file has no model variable.');
    codebook = loaded.model;
end
assert(isstruct(codebook) && isfield(codebook,'S21') && ...
    isfield(codebook,'physicalStates'), 'Invalid codebook.');
originalShape = size(newEnvironmentS21);
cloud = newEnvironmentS21(:);
assert(~isempty(cloud) && isnumeric(cloud) && ...
    all(isfinite(real(cloud)) & isfinite(imag(cloud))), ...
    'Supply finite complex S21 points.');
best = inf(size(cloud));
word = zeros(size(cloud));
for k = 1:numel(codebook.S21)
    trial = abs(cloud + codebook.S21(k));
    improve = trial < best;
    best(improve) = trial(improve);
    word(improve) = k;
end
out = struct('codeword',reshape(word,originalShape), ...
    'sourceStateRow',reshape(codebook.sourceStateRows(word),originalShape), ...
    'diodeBits',codebook.stateBits(word,:), ...
    'fullLoadStates',codebook.physicalStates(word,:), ...
    'touchstoneLoadPorts',codebook.touchstoneLoadPorts, ...
    'selectedS21',reshape(codebook.S21(word),originalShape), ...
    'residualComplex',reshape(cloud+codebook.S21(word),originalShape), ...
    'residualDb',reshape(20*log10(best),originalShape));
end
